language: cpp
install:
  - sudo apt-get install curl
  - sudo apt-get install openssl libssl-dev
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        wget http://www.cmake.org/files/v3.3/cmake-3.3.0-Linux-i386.tar.gz
        tar -xzf cmake-3.3.0-Linux-i386.tar.gz
        sudo cp -fR cmake-3.3.0-Linux-i386/* /usr
      fi
      ;

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.8
script:
  - cmake --version
  - export CXX=$COMPILER;
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON ..
  - make
  - make coveralls
notifications:
  email:
    on_success: change
    on_failure: always