language: cpp
install:
  - sudo apt-get install curl
  - sudo apt-get install openssl libssl-dev
  - wget https://cmake.org/files/v3.7/cmake-3.7.0.tar.gz && tar xzvf cmake-3.7.0.tar.gz && cd cmake-3.7.0 && ./configure --system-curl && make && make install

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.8
script:
  - cmake --version
  - export CXX=$COMPILER;
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON ..
  - make
  - make coveralls
notifications:
  email:
    on_success: change
    on_failure: always