language: c
install:
  - sudo apt-get install curl
script:
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON ..
  - make
  - make coveralls
notifications:
  email:
    on_success: change
    on_failure: always