language: cpp
install:
  - sudo apt-get install curl
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
script:
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON ..
  - make
  - make coveralls
notifications:
  email:
    on_success: change
    on_failure: always