language: cpp
install:
  - sudo apt-get install curl
  - sudo apt-get instal gcc-4.8
  - sudo apt-get install g++-4.8
env: COMPILER=g++-4.8
script:
  - mkdir build && cd build
  - cmake -DCOVERALLS=ON ..
  - make
  - make coveralls
notifications:
  email:
    on_success: change
    on_failure: always