language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target coveralls
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test
notifications:
  email:
    on_success: change
    on_failure: always